services:
    jagilpe_encryption.user_events.subscriber:
        class: Jagilpe\EncryptionBundle\EventListener\UserEventsSubsbriber
        arguments:
            - "@jagilpe_encryption.encryption.service"
        tags:
            - { name: kernel.event_subscriber }
            
    jagilpe_encryption.user_private_key_load_listener:
        class: Jagilpe\EncryptionBundle\EventListener\UserPrivateKeyLoadListener
        arguments:
            - "%jagilpe_encryption.settings%"
            - "@security.token_storage"
            - "@jagilpe_encryption.key_manager"
            - "@jagilpe_encryption.key_store"
            - "@jagilpe_encryption.encryption.service"
        tags:
            - { name: kernel.event_listener, event: kernel.response, priority: 2 }

