services:
    module7_encryption.user_events.subscriber:
        class: Module7\EncryptionBundle\EventListener\UserEventsSubsbriber
        arguments:
            - "@module7_encryption.encryption.service"
        tags:
            - { name: kernel.event_subscriber }
            
    module7_encryption.user_private_key_load_listener:
        class: Module7\EncryptionBundle\EventListener\UserPrivateKeyLoadListener
        arguments:
            - "%module7_encryption.settings%"
            - "@security.token_storage"
            - "@module7_encryption.key_manager"
            - "@module7_encryption.key_store"
            - "@module7_encryption.encryption.service"
        tags:
            - { name: kernel.event_listener, event: kernel.response, priority: 2 }
            
    module7_encryption.web_service_private_key_load_listener:
        class: Module7\EncryptionBundle\EventListener\WebServicePrivateKeyLoadListener
        arguments:
            - "%module7_encryption.settings%"
            - "@security.token_storage"
            - "@module7_encryption.key_manager"
        tags:
            - { name: kernel.event_listener, event: kernel.request }
