services:
    # Encryption services
    eh_encryption.encryption.service:
        class: EHEncryptionBundle\Service\EncryptionService
        arguments:
            - "@doctrine"
            - "@annotation_reader"
            - "@eh_encryption.cryptography_provider"
            - "@eh_encryption.key_manager"
            - "%eh_encryption.settings%"
            
    eh_encryption.cryptography_provider:
        class: EHEncryptionBundle\Crypt\CryptographyProvider
        arguments:
            - "%eh_encryption.settings%"
        
    eh_encryption.key_manager:
        class: EHEncryptionBundle\Crypt\KeyManager
        arguments:
            - "@security.token_storage"
            - "@session"
            - "@eh_encryption.cryptography_provider"
            - "@event_dispatcher"
            - "@eh_encryption.access_checker"
            - "%eh_encryption.settings%"
    
    # default access checker
    eh_encryption.security.access_checker.default:
        class: EHEncryptionBundle\Security\DefaultAccessChecker
        arguments:
            - "%eh_encryption.settings%"
            
    # Event subscribers and listeners
    eh_encryption.doctrine_subscriber:
        class: EHEncryptionBundle\EventListener\EncryptionSubscriber
        arguments:
            - "@eh_encryption.encryption.service"
        tags:
            - { name: doctrine.event_subscriber, connection: default, priority: -10 }
    eh_encryption.user_private_key_load_listener:
        class: EHEncryptionBundle\EventListener\UserPrivateKeyLoadListener
        arguments:
            - "%eh_encryption.settings%"
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: kernel.response, priority: 2 }
