parameters:
    # Metadata drivers
    eh_encryption.metadata.file_locator.class: Metadata\Driver\FileLocator
    eh_encryption.metadata.annotation_driver.class: EHEncryptionBundle\Metadata\Driver\AnnotationDriver
    eh_encryption.metadata.yaml_driver.class: EHEncryptionBundle\Metadata\Driver\YamlDriver
    eh_encryption.metadata.lazy_loading_driver.class: Metadata\Driver\LazyLoadingDriver
    eh_encryption.metadata.chain_driver.class: Metadata\Driver\DriverChain
    eh_encryption.metadata.cache.file_cache.class: Metadata\Cache\FileCache
    
    # Metadata
    eh_encryption.metadata.metadata_factory.class: Metadata\MetadataFactory
    
services:
    # Metadata services
    eh_encryption.metadata.file_locator: 
        class: "%eh_encryption.metadata.file_locator.class%"
        arguments:
            - 
        
    eh_encryption.metadata.yaml_driver: 
        class: "%eh_encryption.metadata.yaml_driver.class%"
        arguments:
            - "@eh_encryption.metadata.file_locator"
            
    eh_encryption.metadata.annotation_driver:
        class: "%eh_encryption.metadata.annotation_driver.class%"
        arguments:
            - "@annotation_reader"

    eh_encryption.metadata.chain_driver:
        class: "%eh_encryption.metadata.chain_driver.class%"
        arguments:
            - ["@eh_encryption.metadata.annotation_driver"]
            
    eh_encryption.metadata_driver:
        alias: "eh_encryption.metadata.chain_driver"
        
    eh_encryption.metadata.lazy_loading_driver:
        class: "%eh_encryption.metadata.lazy_loading_driver.class%"
        arguments:
            - "@service_container"
            - eh_encryption.metadata_driver
    
    eh_encryption.metadata_factory:
        class: "%eh_encryption.metadata.metadata_factory.class%"
        arguments:
            - "@eh_encryption.metadata.lazy_loading_driver"
            - Metadata\ClassHierarchyMetadata
            
    # Encryption services
    eh_encryption.encryption.service:
        class: EHEncryptionBundle\Service\EncryptionService
        arguments:
            - "@eh_encryption.metadata_factory"
            - "@annotation_reader"
            - "@eh_encryption.cryptography_provider"
            - "@eh_encryption.key_manager"
            - "%eh_encryption.settings%"
            
    eh_encryption.cryptography_provider:
        class: EHEncryptionBundle\Crypt\CryptographyProvider
        arguments:
            - "%eh_encryption.settings%"
        
    eh_encryption.key_manager:
        class: EHEncryptionBundle\Crypt\KeyManager
        arguments:
            - "@security.token_storage"
            - "@eh_encryption.cryptography_provider"
            - "@event_dispatcher"
            - "@eh_encryption.access_checker"
            - "%eh_encryption.settings%"
    
    # default access checker
    eh_encryption.security.access_checker.default:
        class: EHEncryptionBundle\Security\DefaultAccessChecker
        arguments:
            - "%eh_encryption.settings%"
            
    # Event subscribers
    eh_encryption.doctrine_subscriber:
        class: EHEncryptionBundle\EventListener\EncryptionSubscriber
        arguments:
            - "@eh_encryption.encryption.service"
        tags:
            - { name: doctrine.event_subscriber, connection: default }
            
    eh_encryption.file_events.subscriber:
        class: EHEncryptionBundle\EventListener\FileEncryptionSubscriber
        arguments:
            - "@eh_encryption.encryption.service"
        tags:
            - { name: "kernel.event_subscriber" }
