services:
    # Encryption services
    module7_encryption.encryption.service:
        class: Module7\EncryptionBundle\Service\EncryptionService
        arguments:
            - "@doctrine"
            - "@annotation_reader"
            - "@module7_encryption.cryptography_provider"
            - "@module7_encryption.key_manager"
            - "@module7_encryption.metadata_factory"
            - "%module7_encryption.settings%"

    module7_encryption.metadata_factory:
        class: Module7\EncryptionBundle\Metadata\ClassMetadataFactory
        arguments:
            - "@annotation_reader"
            - "@doctrine"
            - "@kernel"
            - "%module7_encryption.settings%"

    module7_encryption.cryptography_provider:
        class: Module7\EncryptionBundle\Crypt\CryptographyProvider
        arguments:
            - "%module7_encryption.settings%"
        
    module7_encryption.key_manager:
        class: Module7\EncryptionBundle\Crypt\KeyManager
        arguments:
            - "@security.token_storage"
            - "@session"
            - "@module7_encryption.cryptography_provider"
            - "@module7_encryption.key_store"
            - "@event_dispatcher"
            - "@module7_encryption.access_checker"
            - "@module7_encryption.metadata_factory"
            - "%module7_encryption.settings%"

    module7_encryption.key_store:
        class: Module7\EncryptionBundle\Crypt\KeyStore
        arguments:
            - "@doctrine"
            - "@module7_encryption.cryptography_provider"
            - "%enc_master_key%"

    module7_encryption.decorating_entity_manager:
        class: Module7\EncryptionBundle\Doctrine\ORM\EncryptionEntityManagerDecorator
        decorates: doctrine.orm.default_entity_manager
        arguments: 
            - "@module7_encryption.decorating_entity_manager.inner"
            - "@module7_encryption.encryption.service"
        public: false
    
    # Event subscribers and listeners
    module7_encryption.doctrine_subscriber:
        class: Module7\EncryptionBundle\EventListener\EncryptionSubscriber
        arguments:
            - "@module7_encryption.encryption.service"
        tags:
            - { name: doctrine.event_subscriber, connection: default, priority: -10 }

    # default access checker
    module7_encryption.security.access_checker.default:
        class: Module7\EncryptionBundle\Security\DefaultAccessChecker
        arguments:
            - "%module7_encryption.settings%"

    module7_encryption.security.access_checker.chained:
        class: Module7\EncryptionBundle\Security\ChainedAccessChecker
        arguments:
            - "%module7_encryption.settings%"
