services:
    # Encryption services
    jagilpe_encryption.encryption.service:
        class: Jagilpe\EncryptionBundle\Service\EncryptionService
        arguments:
            - "@doctrine"
            - "@annotation_reader"
            - "@jagilpe_encryption.cryptography_provider"
            - "@jagilpe_encryption.key_manager"
            - "@jagilpe_encryption.metadata_factory"
            - "%jagilpe_encryption.settings%"

    jagilpe_encryption.metadata_factory:
        class: Jagilpe\EncryptionBundle\Metadata\ClassMetadataFactory
        arguments:
            - "@annotation_reader"
            - "@doctrine"
            - "@kernel"
            - "%jagilpe_encryption.settings%"

    jagilpe_encryption.cryptography_provider:
        class: Jagilpe\EncryptionBundle\Crypt\CryptographyProvider
        arguments:
            - "%jagilpe_encryption.settings%"
        
    jagilpe_encryption.key_manager:
        class: Jagilpe\EncryptionBundle\Crypt\KeyManager
        arguments:
            - "@security.token_storage"
            - "@session"
            - "@jagilpe_encryption.cryptography_provider"
            - "@jagilpe_encryption.key_store"
            - "@event_dispatcher"
            - "@jagilpe_encryption.access_checker"
            - "@jagilpe_encryption.metadata_factory"
            - "%jagilpe_encryption.settings%"

    jagilpe_encryption.key_store:
        class: Jagilpe\EncryptionBundle\Crypt\KeyStore
        arguments:
            - "@doctrine"
            - "@jagilpe_encryption.cryptography_provider"
            - "%jagilpe_encryption.master_key%"

    jagilpe_encryption.decorating_entity_manager:
        class: Jagilpe\EncryptionBundle\Doctrine\ORM\EncryptionEntityManagerDecorator
        decorates: doctrine.orm.default_entity_manager
        arguments: 
            - "@jagilpe_encryption.decorating_entity_manager.inner"
            - "@jagilpe_encryption.encryption.service"
        public: false
    
    # Event subscribers and listeners
    jagilpe_encryption.doctrine_subscriber:
        class: Jagilpe\EncryptionBundle\EventListener\EncryptionSubscriber
        arguments:
            - "@jagilpe_encryption.encryption.service"
        tags:
            - { name: doctrine.event_subscriber, connection: default, priority: -10 }

    # default access checker
    jagilpe_encryption.security.access_checker.default:
        class: Jagilpe\EncryptionBundle\Security\DefaultAccessChecker
        arguments:
            - "%jagilpe_encryption.settings%"

    jagilpe_encryption.security.access_checker.chained:
        class: Jagilpe\EncryptionBundle\Security\ChainedAccessChecker
        arguments:
            - "%jagilpe_encryption.settings%"
